USE customer_behaviour;
SELECT * FROM customer;


-- 1. what is total revenue generated by male vs female

SELECT gender ,SUM(purchase_amount) as revenue
FROM customer 
GROUP BY gender;

-- 2. which customers used a discount code but still spent more that the avregae purchase amount

SELECT *
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >=(SELECT AVG(purchase_amount) as avg FROM customer);

-- 3.Which are the top 5 products with highest average review rating

SELECT item_purchased , ROUND(AVG(review_rating),2) as avg_review
FROM customer
GROUP BY item_purchased
ORDER BY avg_review DESC
LIMIT 5;

-- 4.Compare the avregae purcahse amount between standard and express shipping

SELECT shipping_type , AVG(purchase_amount) as avg_purchase_shipping
FROM customer
GROUP BY shipping_type
HAVING shipping_type IN ('Standard','Express')
ORDER BY avg_purchase_shipping DESC;

-- 5.Do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
COUNT(customer_id) as count_of_customer,
AVG(purchase_amount) as avg_purchase , 
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY subscription_status;

-- 6.Which 5 products  have the highest percentage of purchase with discount applied
SELECT item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- 7.Segment customers into new , returning and loyal based on their total number of previous purchases and show the count of each segment

with customer_type as(
  SELECT customer_id,previous_purchases,
  CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
    ELSE 'Loyal'
	END as customer_segment
  FROM customer
)
SELECT customer_segment,COUNT(*) as number_of_customers
FROM customer_type
GROUP BY customer_segment;


-- 8. What are top 3 products purchased within each category

WITH item_counts as(
	SELECT category,item_purchased,
    COUNT(customer_id) as total_count,
    ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
	FROM customer
    GROUP BY category,item_purchased    
)
SELECT * FROM item_counts
WHERE item_rank < 4;


-- 9.Are customers who are repeat buyers (more than 5 previous purchases) are likely to subscribe

SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer 
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10 What is revenue contribution of each age group

SELECT age_group,SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;